// 18-React/02-React进阶/13-Router/02-嵌套路由/pages/Home.jsx
import React from 'react'
import { NavLink, Outlet } from 'react-router-dom'

export default function Home() {
  return (
    <div>
      <h2>Home组件内容</h2>
      <div>
        <ul className="nav nav-tabs">
          <li>
            <NavLink className="list-group-item" to="/home/news">News</NavLink>
          </li>
          <li>
            <NavLink className="list-group-item" to="/home/message">Message</NavLink>
          </li>
        </ul>
        {/* 指定路由展示的位置 */}
        <Outlet />
      </div>
    </div>
  )
}

// 15-Vue/02-Vue进阶/02-component/src08_router/pages/Home.vue
<template>
	<div>
		<h2>Home</h2>
		<ul class="nav nav-tabs">
			<li>
				<!-- 路由链接 -->
				<router-link to="/home/news">News</router-link>
			</li>
			<li>
				<!-- 路由链接 -->
				<router-link to="/home/message">Message</router-link>
			</li>
		</ul>
		<!-- 在此显示二级路由组件 -->
		<router-view></router-view>
	</div>
</template>
<script>
export default {
	name: 'Home',
}
</script>
<style scoped></style>
