// 15-Vue/2.VUE组件/2.component/src/pages/Message.vue
<template>
	<div>
		<ul>
			<li v-for="m in messages" :key="m.id">
				<router-link to="path">{{ m.title }}</router-link>
			</li>
		</ul>
	</div>
</template>
<script>
export default {
	data() {
		return {
			messages: [],
		}
	},
	mounted() {
		// 模拟请求获取message
		setTimeout(() => {
			const messages = [
				{ id: 1, title: 'messages001' },
				{ id: 2, title: 'messages002' },
				{ id: 3, title: 'messages003' },
			]
			// 更新数据
			this.messages = messages
		}, 1000)
	},
}
</script>
<style scoped></style>

// 18-React/02-React进阶/13-Router/04-search参数/pages/Message.jsx
import React, { useState } from 'react'
import { Link, Outlet } from 'react-router-dom'

export default function Message() {
  const [messages] = useState([
    { id: '1', title: '消息1', content: '内容1' },
    { id: '2', title: '消息2', content: '内容2' },
    { id: '3', title: '消息3', content: '内容3' },
  ])
  return (
    <div>
      <ul>
        {
          messages.map((item) => {
            return (
              <li key={item.id}>
                <Link to={`detail?id=${item.id}&title=${item.title}&content=${item.content}`}>{item.content}</Link>
              </li>
            )
          })
        }
      </ul>
      <hr />
      {/* 指定路由展示的位置 */}
      <Outlet />
    </div>
  )
}
